<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-04-27 18:30

$extensionPath = t3lib_extMgm::extPath('dhdbmm');
return array(
);
?>